version: '3.8'

services:
  traefik:
    image: "traefik:v2.6"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      #- "--certificatesresolvers.mytlschallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.mytlschallenge.acme.email=marc@becheftigt.de"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8088:8080"
    volumes:
      - "./volumes/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  dancer:
    image: dancier/dancer:1.0
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dancer.rule=Host(`dancer.dancier.net`)"
      - "traefik.http.routers.dancer.entrypoints=websecure"
      - "traefik.http.routers.dancer.tls.certresolver=mytlschallenge"
    environment:
      SPRING_PROFILES_ACTIVE: staging
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      APP_AUTH_TOKENSECRET: ${APP_AUTH_TOKENSECRET}
      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS}
      APP_MAIL_USER: ${APP_MAIL_USER}
      APP_MAIL_PASS: ${APP_MAIL_PASS}
      APP_CAPTCHA_APIKEY: ${APP_CAPTCHA_APIKEY}
    volumes:
      - ./volumes/dancer-media/images:/images-dir
    depends_on:
      - dancer-db
      - traefik

  dancer-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DANCER_DB_USER}
      POSTGRES_PASSWORD: ${DANCER_DB_PASSWORD}
      POSTGRES_DB: ${DANCER_DB_DB}
    volumes:
      - ./volumes/dancer-data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.dancier.net`)"
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pgadmin.tls.certresolver=mytlschallenge"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dancier.net
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    depends_on:
      - dancer-db
      - traefik
    volumes:
      - ./volumes/pg-admin-data:/var/lib/pgadmin

  show-dancer:
    image: dancier/show-dancer:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.show-dancer.rule=Host(`dancier.net`)"
      - "traefik.http.routers.show-dancer.entrypoints=websecure"
      - "traefik.http.routers.show-dancer.tls.certresolver=mytlschallenge"
    depends_on:
      - traefik

  tool:
    image: ubuntu
    restart: always
    stdin_open: true
