version: '3.8'

services:

  dancer:
    build: ./
    ports:
      - "8080:8080"
      - "8081:8081"
      - "5005:5005"
    depends_on:
      - dancer-db
    environment:
#   https://ckinan.com/blog/remote-debug-spring-boot-docker-intellij/:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  dancer-db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dancer
      POSTGRES_PASSWORD: dancer
      POSTGRES_DB: dancer
    volumes:
      - ./volumes/dancer-data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:6.15
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dancier.net
      PGADMIN_DEFAULT_PASSWORD: secret
    volumes:
      - ./volumes/pg-admin-data:/var/lib/pgadmin

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

