version: '3.8'

services:
  dancer:
    image: dancier/dancer:1.0
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      APP_AUTH_TOKENSECRET: ${APP_AUTH_TOKENSECRET}
      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS}
      APP_redirectAfterEmailValidation: ${APP_redirectAfterEmailValidation}
    depends_on:
      - dancer-db

  dancer-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DANCER_DB_USER}
      POSTGRES_PASSWORD: ${DANCER_DB_PASSWORD}
      POSTGRES_DB: ${DANCER_DB_DB}
    volumes:
      - ./volumes/dancer-data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dancier.net
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    depends_on:
      - dancer-db
    volumes:
      - ./volumes/pg-admin-data:/var/lib/pgadmin