# Author: Marc Gorzala
version: "3.9"
services:
  traefik:
    image: ${TRAEFIK_IMAGE}
    command:
      - "--log.level=${TRAEFIK_LOG_LEVEL}"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      #- "--certificatesresolvers.mytlschallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.mytlschallenge.acme.email=${ACME_MAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    restart: always
    ports:
      - "443:443"
    volumes:
      - "${VOLUMES_LETSENCRYPT}:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  dancer:
    image: ${DANCER_IMAGE}
    restart: always
    volumes:
      - "./config.yml:/config.yml"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dancer.rule=Host(`${DANCER_HOSTNAME}`)"
      - "traefik.http.routers.dancer.entrypoints=websecure"
      - "traefik.http.routers.dancer.tls.certresolver=mytlschallenge"
    environment:
      - DW_DB_JDBC_URL=jdbc:postgresql://postgres/dancier
      - DW_LOGIN_FACEBOOK_CLIENT_SECRET
    depends_on:
      - postgres
      - traefik
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=dancier
    restart: always
