openapi: '3.0.2'
info:
  title: dancer
  version: '1.0'
servers:
  - url: https://dancer.dancier.net
paths:
  /login:
    get:
      responses:
        '200':
          description: OK
  /image:
    get:
      responses:
        '200':
          description: The image
    post:
      responses:
        '201':
          description: image was created
  /profile:
    get:
      responses:
        "200":
          description: "The profile"      
        "401":
          description: "Unauthenticated"
        "404":
          description: "Not found"
    post:
      responses:
        "200":
          description: update
  /recommendations:
    get:
      responses:
        '200':
          description: |
            Everthing dancier could recommend to
            a dancer. 
                        
            This could be
              * a dancing school
              * an event to dance
              * ...
        '400':
          description: |
            In case, the user has not filled out the profile, we 
            can not compute any recommendations.
            In this case we return a 400.
        '404':
          description: "Unauthenticated"