openapi: 3.0.2
info:
  title: dancer
  version: '1.0'
servers:
  - url: 'https://dancer.dancier.net'
paths:
  /login:
    get:
      responses:
        '200':
          description: OK
  /image:
    get:
      responses:
        '200':
          description: The image
    post:
      responses:
        '201':
          description: image was created
  /profile:
    get:
      responses:
        '200':
          description: The profile
        '401':
          description: Unauthenticated
        '404':
          description: Not found
