spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/dancer
    username: dancer
    password: dancer
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:liquibase-changeLog.xml
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 15MB
      max-request-size: 17MB
  test:
    database:
      replace: none
  profiles:
    default: dev
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:4200 # Comma separated list of allowed origins
  # differentiate between success and failure
  mail:
    host: mail.your-server.de
    port: 465
    user: user
    pass: pass
    allForOneAddress: dev@dancier.net
  file:
    dir: ./images-dir
  captcha:
    siteKey: 6LetqBAgAAAAAJXA5K_U88bsxKtyp_vld6J0x-Nv
    apiKey: secret
logging:
  level:
    root: INFO
    net:
      dancier: DEBUG
    org:
      hibernate:
        SQL: DEBUG