spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dancer

app:
  s3:
    active: false
  recommendation:
    host: http://test.dancier.net:5000
  chatDancer:
    host: http://test.dancier.net:9999

